name: mobile_anemia_detector
description: Aplicativo móvel para diagnóstico de anemia em ovinos usando Machine Learning on-device
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Machine Learning
  tflite_flutter: ^0.12.1
  
  # Manipulação de Imagens
  image_picker: ^1.0.7
  image_cropper: ^11.0.0
  image: ^4.1.7
  camera: ^0.11.0+2
  
  # Utilitários
  path_provider: ^2.1.1
  path: ^1.8.3
  provider: ^6.0.5
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  fl_chart: ^0.66.2
  printing: ^5.12.0
  pdf: ^3.10.8
  csv: ^6.0.0
  share_plus: ^10.0.2
  intl: ^0.19.0
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  
  assets:
    - assets/model.tflite
    - assets/images/

